[tool.poetry]
name = "ice-cream-dataops"
version = "0.1.0"
description = ""
authors = ["shotin <shotin93@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.10"
cognite-toolkit = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
